# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 02:55
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pyconkr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=b'profile'),
        ),
    ]
